spring:
  application:
    name: "spring-1team"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  default-consume-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-my-super-secret-key-123456}
  access-token-expiration-ms: 3600000